export const ADD_BUNS = "ADD_BUNS";
export const ADD_ITEMS = "ADD_ITEMS";
export const DELETE_CONSTRUCTOR_ITEM = "DELETE_CONSTRUCTOR_ITEM";
export const SORT_CONSTRUCTOR_ITEMS = "SORT_CONSTRUCTOR_ITEMS";
export const RESET_CONSTRUCTOR = 'RESET_CONSTRUCTOR';